export default [
{
  id: '1',
  baseCoin: 'BTC',
  tradeCoin: 'ETH',
  tradeValue: 0.05020,
  baseCoinName: 'Bitcoin',
  tradeCoinName: 'Ethereum',
  percentGrowth: 0.21,
  baseCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  tradeCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/1.jpg',
}, {
  id: '2',
  baseCoin: 'ETH',
  tradeCoin: 'USD',
  tradeValue: 2523.32,
  baseCoinName: 'Ethereum',
  tradeCoinName: 'US Dollars',
  percentGrowth: 1.37,
  baseCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  tradeCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/1.jpg',
}, {
  id: '3',
  baseCoin: 'BTC',
  tradeCoin: 'USD',
  tradeValue: 37102.09,
  baseCoinName: 'Bitcoin',
  tradeCoinName: 'US Dollars',
  percentGrowth: -1.41,
  baseCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  tradeCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/1.jpg',
}, {
  id: '4',
  baseCoin: 'BTC',
  tradeCoin: 'DASH',
  tradeValue: 0.09821,
  baseCoinName: 'Bitcoin',
  tradeCoinName: 'Dash',
  percentGrowth: 0.91,
  baseCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  tradeCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/1.jpg',
}, {
  id: '5',
  baseCoin: 'BTC',
  tradeCoin: 'DGB',
  tradeValue: 0.00124,
  baseCoinName: 'Bitcoin',
  tradeCoinName: 'DigiByte',
  percentGrowth: 0.11,
  baseCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  tradeCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/1.jpg',
}, {
  id: '6',
  baseCoin: 'DGB',
  tradeCoin: 'USD',
  tradeValue: 0.110012,
  baseCoinName: 'DigiByte',
  tradeCoinName: 'US Dollars',
  percentGrowth: -0.053,
  baseCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  tradeCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/1.jpg',
}, {
  id: '7',
  baseCoin: 'XMR',
  tradeCoin: 'USD',
  tradeValue: 162.92,
  baseCoinName: 'Monero',
  tradeCoinName: 'US Dollars',
  percentGrowth: 2.31,
  baseCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  tradeCoinImg: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/1.jpg',
}]