export default [{
  id: '1',
  name: 'ItemOne',
  desc: 'Buy Option One',
  image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  price: 0.99,
  checkoutLink: '',
}, {
  id: '2',
  name: 'ItemTwo',
  desc: 'Buy Option Two',
  image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  price: 4.99,
  checkoutLink: '',
}, {
  id: '3',
  name: 'ItemThree',
  desc: 'Buy Option Three',
  image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  price: 9.99,
  checkoutLink: '',
}, {
  id: '4',
  name: 'ItemFour',
  desc: 'Buy Option Four',
  image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  price: 19.99,
  checkoutLink: '',
}, {
  id: '5',
  name: 'ItemFive',
  desc: 'Buy Option Five',
  image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
  price: 49.99,
  checkoutLink: '',
}]